import {
  ActivityLog,
  CompetitorPrice,
  InvestmentOption,
  MarketTicker,
  ProjectionPoint,
  SharedGoal,
  Subscription,
  TrustFactor,
  User,
  WealthScoreFactor,
} from "./types";

export const INITIAL_USER: User = {
  id: "usr_99841",
  name: "Alex Mercer",
  email: "alex.mercer@vibeforge.ai",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  role: "Pro",
  demoPreset: "Balanced Wealth",
  savingsGoal: "MacBook Pro M3 Max Emergency Fund",
  goalTargetAmount: 150000,
  goalCurrentAmount: 98500,
  createdTime: "2026-01-15",
};

export const WEALTH_SCORE_FACTORS: WealthScoreFactor[] = [
  {
    id: "f1",
    name: "Savings & Cashflow Rate",
    score: 84,
    weight: 0.25,
    advice: "Saving 24% of monthly net income. Auto-roundups adding ₹1,850/mo.",
    category: "cashflow",
  },
  {
    id: "f2",
    name: "Emergency Reserve Ratio",
    score: 78,
    weight: 0.2,
    advice: "5.2 months of living expenses secured in liquid debt funds.",
    category: "emergency",
  },
  {
    id: "f3",
    name: "Debt-to-Income Index",
    score: 92,
    weight: 0.2,
    advice: "Low credit utilization (8.5%). Zero high-interest credit card debt.",
    category: "debt",
  },
  {
    id: "f4",
    name: "Portfolio Diversification",
    score: 65,
    weight: 0.2,
    advice: "High concentration in equity index funds. Sovereign Gold allocated 8%.",
    category: "diversification",
  },
  {
    id: "f5",
    name: "Impulse Shopping Shield Index",
    score: 88,
    weight: 0.15,
    advice: "Saved ₹14,200 last month by accepting 4 impulse checkout warnings.",
    category: "impulse",
  },
];

export const INVESTMENT_OPTIONS: InvestmentOption[] = [
  {
    id: "inv_1",
    title: "Nifty 50 Index Quality Fund",
    category: "Index Funds",
    expectedReturn: 12.8,
    riskProfile: "balanced",
    minSip: 500,
    matched: true,
    tags: ["Top 50 India", "Low Expense Ratio", "High Liquidity"],
    description: "Low-cost index fund tracking India's top 50 blue-chip companies with historic 10y stability.",
    marketSymbol: "NIFTY50",
    currentPrice: 24320,
  },
  {
    id: "inv_2",
    title: "Sovereign Gold Bond (SGB 2026-Series)",
    category: "Sovereign Gold",
    expectedReturn: 9.5,
    riskProfile: "conservative",
    minSip: 1000,
    matched: true,
    tags: ["2.5% Fixed Interest", "Tax Free Capital Gains", "RBI Backed"],
    description: "Government-backed gold investment with regular biannual interest payouts and tax-exempt maturity.",
    marketSymbol: "GOLD_SGB",
    currentPrice: 7250,
  },
  {
    id: "inv_3",
    title: "Flexi-Cap Tech & Alpha Equity",
    category: "Equity Funds",
    expectedReturn: 16.4,
    riskProfile: "aggressive",
    minSip: 1000,
    matched: false,
    tags: ["High Alpha", "Mid & Large Cap", "Technology Overweight"],
    description: "Actively managed equity fund targeting disruptive technology and high-growth mid-cap leaders.",
    marketSymbol: "FLEXI_ALPHA",
    currentPrice: 184.5,
  },
  {
    id: "inv_4",
    title: "Short Duration Liquid Debt Fund",
    category: "Debt Funds",
    expectedReturn: 7.2,
    riskProfile: "conservative",
    minSip: 500,
    matched: true,
    tags: ["Instant Redemption", "Capital Protection", "Zero Lock-in"],
    description: "Ultra-safe AAA-rated corporate debt & treasury bill portfolio ideal for emergency cash reserves.",
    marketSymbol: "LIQUID_AAA",
    currentPrice: 1120,
  },
  {
    id: "inv_5",
    title: "ESG India Clean Energy Fund",
    category: "Equity Funds",
    expectedReturn: 14.8,
    riskProfile: "balanced",
    minSip: 500,
    matched: true,
    tags: ["Green Energy", "Solar & EV Infrastructure", "Future Growth"],
    description: "Targeted ESG fund focused on India's top renewable energy grid and EV battery leaders.",
    marketSymbol: "ESG_GREEN",
    currentPrice: 94.2,
  },
];

export const INITIAL_SIP_MONTHLY = 1850; // auto-roundups amount

export const SIP_PROJECTIONS: ProjectionPoint[] = [
  { year: 1, conservative: 23100, balanced: 23550, aggressive: 24020 },
  { year: 2, conservative: 47900, balanced: 49750, aggressive: 51600 },
  { year: 3, conservative: 74500, balanced: 78900, aggressive: 83400 },
  { year: 4, conservative: 103200, balanced: 111300, aggressive: 120200 },
  { year: 5, conservative: 134000, balanced: 147300, aggressive: 162600 },
  { year: 6, conservative: 167200, balanced: 187400, aggressive: 211500 },
  { year: 7, conservative: 202800, balanced: 231900, aggressive: 267900 },
  { year: 8, conservative: 241100, balanced: 281300, aggressive: 333000 },
  { year: 9, conservative: 282300, balanced: 336300, aggressive: 408100 },
  { year: 10, conservative: 326600, balanced: 397400, aggressive: 494800 },
];

export const COMPETITOR_PRICES: CompetitorPrice[] = [
  {
    id: "cp1",
    merchant: "TechDeals Direct",
    price: 8499,
    inStock: true,
    shippingDays: 2,
    couponCode: "VAULT500",
    discountPercent: 6,
  },
  {
    id: "cp2",
    merchant: "GigaElectronics",
    price: 8999,
    inStock: true,
    shippingDays: 1,
    couponCode: "SAVE10",
    discountPercent: 10,
  },
  {
    id: "cp3",
    merchant: "CyberMarket India",
    price: 9299,
    inStock: false,
    shippingDays: 5,
  },
  {
    id: "cp4",
    merchant: "FlashStore Official",
    price: 8250,
    inStock: true,
    shippingDays: 3,
    couponCode: "FLASHBEST",
    discountPercent: 8,
  },
];

export const TRUST_FACTORS: TrustFactor[] = [
  {
    id: "tf1",
    name: "Review Authenticity & NLP Sentiment",
    score: 94,
    status: "Good",
    description: "Verified buyers only. Zero bot cluster pattern detected in past 90 days.",
  },
  {
    id: "tf2",
    name: "Domain Longevity & SSL Security",
    score: 98,
    status: "Good",
    description: "Domain active for 7+ years with EV SSL certificate.",
  },
  {
    id: "tf3",
    name: "Return & Refund SLA Compliance",
    score: 72,
    status: "Moderate",
    description: "7-day replacement window. Restocking fee may apply on opened electronics.",
  },
  {
    id: "tf4",
    name: "Delivery Track Record",
    score: 88,
    status: "Good",
    description: "96.4% on-time fulfillment via trusted courier partners.",
  },
];

export const INITIAL_SUBSCRIPTIONS: Subscription[] = [
  {
    id: "sub_1",
    name: "CloudDrive Ultra Storage (2TB)",
    amount: 650,
    billingCycle: "Monthly",
    status: "Active",
    category: "Software",
    lastChargedDate: "2026-08-01",
    autoFlagged: false,
  },
  {
    id: "sub_2",
    name: "CineFlex Streaming 4K Pass",
    amount: 799,
    billingCycle: "Monthly",
    status: "Active",
    category: "Entertainment",
    lastChargedDate: "2026-07-28",
    autoFlagged: false,
  },
  {
    id: "sub_3",
    name: "Mystery Gaming Loot Vault",
    amount: 1499,
    billingCycle: "Monthly",
    status: "Suspicious",
    category: "Unknown",
    lastChargedDate: "2026-08-04",
    disputeReason: "Recurring transaction auto-renewed without explicit prior notification email.",
    autoFlagged: true,
  },
  {
    id: "sub_4",
    name: "FitPulse Gym & Health Pass",
    amount: 1999,
    billingCycle: "Monthly",
    status: "Forgotten",
    category: "Fitness",
    lastChargedDate: "2026-06-12",
    disputeReason: "Zero gym check-ins detected in over 58 consecutive days.",
    autoFlagged: true,
  },
  {
    id: "sub_5",
    name: "AI Writer Pro Assistant",
    amount: 1250,
    billingCycle: "Monthly",
    status: "Forgotten",
    category: "Software",
    lastChargedDate: "2026-05-30",
    disputeReason: "Replaced by VaultPulse Copilot. Inactive for 70+ days.",
    autoFlagged: true,
  },
];

export const SHARED_GOALS: SharedGoal[] = [
  {
    id: "sg_1",
    title: "Family Emergency Reserve Pool",
    targetAmount: 300000,
    currentAmount: 215000,
    category: "Emergency Fund",
    deadline: "2026-12-31",
    contributors: [
      { name: "Alex Mercer", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80", contribution: 125000 },
      { name: "Sarah Mercer", avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80", contribution: 90000 },
    ],
  },
  {
    id: "sg_2",
    title: "Japan Tech & Culinary Trip 2027",
    targetAmount: 250000,
    currentAmount: 142000,
    category: "Vacation",
    deadline: "2027-04-15",
    contributors: [
      { name: "Alex Mercer", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80", contribution: 71000 },
      { name: "Dev Team Partner", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80", contribution: 71000 },
    ],
  },
];

export const INITIAL_ACTIVITIES: ActivityLog[] = [
  {
    id: "act_1",
    timestamp: "10 mins ago",
    title: "AI Impulse Shield Activated",
    description: "Saved ₹850 coupon on TechDeals Direct checkout. Warned impulse buy.",
    category: "extension",
    type: "success",
  },
  {
    id: "act_2",
    timestamp: "1 hour ago",
    title: "Dispute Draft Generated",
    description: "Drafted formal dispute for Mystery Gaming Loot Vault (₹1,499).",
    category: "action",
    type: "warning",
  },
  {
    id: "act_3",
    timestamp: "3 hours ago",
    title: "Auto-Save Round-Up Deposited",
    description: "₹142 saved from shopping transactions routed to Nifty 50 Index.",
    category: "wealth",
    type: "info",
  },
  {
    id: "act_4",
    timestamp: "Yesterday",
    title: "Shared Goal Milestone",
    description: "Family Emergency Pool hit 71% completion milestone!",
    category: "collaboration",
    type: "success",
  },
];

export const MARKET_TICKERS: MarketTicker[] = [
  { symbol: "NIFTY 50", name: "NSE India Index", price: 24345.8, changePercent: 1.24, type: "Index" },
  { symbol: "SGB GOLD", name: "Sovereign Gold Bond", price: 7280.0, changePercent: 0.45, type: "Gold" },
  { symbol: "S&P 500", name: "US Tech Index", price: 5410.2, changePercent: 0.88, type: "Index" },
  { symbol: "BTC/INR", name: "Bitcoin Vault", price: 5642000, changePercent: -0.62, type: "Crypto" },
];
